namespace NWindows
{
    public enum NKeyCode
    {
        Unknown = 0,

        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,

        Escape,

        Grave,
        Key0,
        Key1,
        Key2,
        Key3,
        Key4,
        Key5,
        Key6,
        Key7,
        Key8,
        Key9,
        Minus,
        Plus,
        Backspace,

        Tab,
        LeftBracket,
        RightBracket,
        Backslash,

        Semicolon,
        Apostrophe,
        Enter,

        Comma,
        Period,
        Slash,

        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,

        Space,

        LeftShift,
        RightShift,
        LeftControl,
        RightControl,
        LeftAlt,
        RightAlt,

        LeftWindows,
        RightWindows,
        Applications,

        CapsLock,
        ScrollLock,
        PrintScreen,
        Pause,

        Home,
        End,
        PageUp,
        PageDown,
        Insert,
        Delete,

        LeftArrow,
        RightArrow,
        UpArrow,
        DownArrow,

        NumPadNumLock,

        NumPadHome,
        NumPadEnd,
        NumPadPageUp,
        NumPadPageDown,
        NumPadInsert,
        NumPadDelete,
        NumPadLeftArrow,
        NumPadRightArrow,
        NumPadUpArrow,
        NumPadDownArrow,
        NumPadClear,
        NumPadEnter,
        NumPad0,
        NumPad1,
        NumPad2,
        NumPad3,
        NumPad4,
        NumPad5,
        NumPad6,
        NumPad7,
        NumPad8,
        NumPad9,
        NumPadAdd,
        NumPadSubtract,
        NumPadMultiply,
        NumPadDivide,
        NumPadDecimal
    }
}